### ISSUE TITLE
How to get an anonymized dump using tidus?

### ISSUE THREAD

**Issue by ArneZsng** [Barzahlen/tidus#5]
I took a look at your gem and think the approach is interesting though I am a little unclear how it would solve the problem you described in the first paragraphs. Say we would like to reproduce an error on a local dev machine or our staging environment, how would the views help us?

Do you export a dump for the whole DB based on the obfuscated data in the views? Or would you move your whole production DB from your production server to your staging server (so that it contains the original, unanonymized content as well but is not accessible by the staging server)? Basically, our goal is to easily export a current dump directly from production that contains anonymized data without going through the hassle and potential threat of storing it locally, applying anonmyzation and dumping it again. Could you give me an insight in the larger picture you imagined / are using the gem in?

**Comment by martinseener** [comment]
Our production data contains some sensitive information.
We never want those information to leave the production databases and move on to the staging or local development databases.

Our solution is to create views which allow live anonymization/obfuscation of the data, so that the real data never has to leave the production db. We create a view for every table (except schema_migrations, since we do not have an AR model for those ;-)) and let the developer add anonymization rules in the AR model.
During the next deployment the views are generated again with the updated rules.
(In case you are wondering why the devs: The communication about database changes to our admin wasn't always perfect and sometimes we forgot to update the views which would break our staging restore - since devs build migrations anyways they can add anonymization while they are at it)

Unfortunately pg_dump does not allow dumping views directly.
Therefore we only dump the schema using pg_dump and the data using COPY (http://www.postgresql.org/docs/9.2/static/sql-copy.html).
Keep in mind: since the views are regenerated during each deployment you have to set permissions if your dump db user differs from the general user (e.g. if you want to restrict access to unanonymized data)

Our current flow is as follows: anonymized dumps are regularly created. We also got a job to trigger an anonymized dump with the current data. Furthermore we got a job to trigger a restore to staging (which allows selecting which of the currently retained dumps to restore)
For devs we got a script which can load the current staging data to the local machine.

For debugging this approach has the advantage that you can get data close to the stuff that failed. You have to keep in mind though, that the anonymization rules may hide the actual faulty data! (e.g. when a value is NULL in production,  but is overwritten in the view).

For testing new features this approach has the advantage that you can get a consistent dataset without having to add entries in several tables/databases just so that a minor change can be manually tested.

The usage of the example script is quite easy despite the script's not very pretty. Just call the script with the parameter -d for dump or -r for restore followed by the path to be used for saving the dumps or getting the dumps for restore. This folder is normally the same for both depending on the environment. For restore you also have to tell the script which backup-set you want to restore. The dumping part will do 7 rolling dumps (so for 7 days when called once a day for example).

While this script is pretty basic and not initially written for easy public use you have to change the server ip, port, user and password within the script as well as the database names for dumping and restore. Just check the dump_it, restore_it, dump_db and restore_db functions. I will release a refactored version later but you can start with this one as it works quite well for us for the last year.

**Comment by ArneZsng** [comment]
Hi Martin,

Thank you for this in depth explanation. We were using the "old" approach until recently by downloading a full production dump, anonymizing it through the data-anonymization gem (https://github.com/sunitparekh/data-anonymization) and distributing this version. However, the gem dependency caused some trouble and it didn't really feel like a smart solution to the problem. I will keep you posted on our progress implementing tidus.

Best,
Arne

**Comment by martinseener** [comment]
Hi Arne,

we had no good solution initially either so i developed a method to do this half-manually by defining the views by hand for tables which had data to be anonymized and dumped that afterwards. Later as we saw that this was no good "automation" too we developed tidus which does all the dirty work for us and we started to ONLY use the views it creates - either with or without anonymization. We use tidus and the example script now for some months now without any issues. It works great!

Sure, the dump/restore script is not very easy to read though but it does its work and we have an enhanced version internally which has some more features and i'll try to refactor this script here for more readability and easier handling as well as some more features. I'll also add another script we use in our development vagrant boxes for live-dumping & restoring into the vagrant box directly. So stay tuned - there will be updates here soon.

In the meantime, have fun using tidus and if you have any questions, let us know or if you have enhancement to either the gem or the script, we happily accept contributions!

Best, Martin
